<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="NhaSX.aspx.cs" Inherits="MobileStoreOnline.Admin.NhaSX" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
    <div class="panel-heading">
        <h4 class="panel-title text-center">Quản lý sản phẩm</h4>
    </div>
    <div class="panel-body">
        <form runat="server" enctype="multipart/form-data">
            <%--Thêm sản phẩm--%>
            <div class="row text-center">
                <asp:Label ID="error" runat="server" Text="" CssClass="small alert-danger" />
            </div>
            <div class="row hidden-xs">
                <div class="container col-xs-12">
                    <div class="form-group row">
                        <label class="col-xs-4 text-right">Tên nhà sản xuất:</label>
                        <div class="col-xs-4">
                            <asp:TextBox ID="TenNSX" runat="server" CssClass="form-control" />
                        </div>
                    </div>
                    <div class="text-center">
                        <asp:Button ID="addNSX" runat="server" Text="Thêm hãng" CssClass="btn btn-primary" OnClick="addNSX_Click"/>
                    </div>
                </div>
            </div>
            <%--Thay đổi sản phẩm--%>
            <div class="row">
                <div class="col-md-12">
                    <asp:Label ID="lblMessage" runat="Server" ForeColor="Red"></asp:Label><br />
                    <asp:GridView ID="gvNSX" AutoGenerateColumns="false" HeaderStyle-CssClass="info" runat="server" CssClass="table table-responsive table-condensed table-striped table-bordered table-hover"  AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" DataKeyNames="MaSX" OnRowEditing="gvNhaSanXuat_RowEditing" OnRowCancelingEdit="gvNhaSanXuat_RowCancelingEdit" OnRowUpdating="gvNhaSanXuat_RowUpdating" OnRowDeleting="gvNhaSanXuat_RowDeleting">
                        <Columns>
                            <asp:BoundField DataField="MaSX" HeaderText="Mã sản phẩm" ReadOnly="True"/>
                            <asp:BoundField DataField="TenSX" HeaderText="Nhà sản xuất"/>
                        </Columns>
                    </asp:GridView>
                </div>
            </div>
        </form>
    </div>
</asp:Content>
